[package]
name = "example-build"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
educe = "0.4.20"
serde = "1.0"
serde_json = "1.0.91"

[build-dependencies]
schemars = "0.8"
serde_json = "1.0.91"
typify = { path = "../typify" }
