[package]
name = "typify-test"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
educe = "0.4.20"
regress = "0.4.1"
serde = "1.0.152"
serde_json = "1.0.91"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
schemars = "0.8.11"
serde = "1.0.152"
typify = { path = "../typify" }
