[package]
name = "example-macro"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
educe = "0.4.20"
typify = { path = "../typify" }
serde = "1.0"
serde_json = "1.0"
